drdoh_ticket_billetterie:
    path:     /
    defaults: { _controller: DrdohLouvreBundle:Billetterie:index }

# dr_doh_ticket_billetterie_stipe:
#     path:     /payement
#     defaults: { _controller: DrDohTicketBundle:Booking:stripeForm }

# dr_doh_ticket_billetterie_stipe_checkout:
#     path:     /checkout
#     defaults: { _controller: DrDohTicketBundle:Booking:stripeCheckout }

# dr_doh_ticket_billetterie_sending_ticket:
#     path:     /sendPdf/{orderId}
#     defaults: { _controller: DrDohTicketBundle:Booking:sendingTicket }